# version: "3.8"

services:
  db:
    image: postgis/postgis:16-3.4 # PostgreSQL 16 with PostGIS 3.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_database
    ports:
      - "7001:5432"
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
